<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menProducts = [
            [
                'name' => 'Aurum',
                'description' => 'Matte Black • Classic Design',
                'category' => 'men',
                'type' => 'frame',
                'price' => 199,
                'old_price' => null,
                'image_path' => 'frames/men/aurum.avif',
                'badge' => 'Bestseller',
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Creston',
                'description' => 'Tortoiseshell • Bold Acetate',
                'category' => 'men',
                'type' => 'frame',
                'price' => 259,
                'old_price' => null,
                'image_path' => 'frames/men/creston.avif',
                'badge' => null,
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Imperio',
                'description' => 'Premium Gold Frame • Unisex',
                'category' => 'men',
                'type' => 'frame',
                'price' => 249,
                'old_price' => null,
                'image_path' => 'frames/men/imperio.jpg',
                'badge' => 'New',
                'badge_color' => '#eab308',
            ],
            [
                'name' => 'Monarch',
                'description' => 'Silver Metal • Classic Aviator',
                'category' => 'men',
                'type' => 'frame',
                'price' => 279,
                'old_price' => null,
                'image_path' => 'frames/men/monarch.jpg',
                'badge' => 'Bestseller',
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Noirline',
                'description' => 'Dark Blue • Sophisticated',
                'category' => 'men',
                'type' => 'frame',
                'price' => 239,
                'old_price' => null,
                'image_path' => 'frames/men/noirline.avif',
                'badge' => null,
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Regalis',
                'description' => 'Gunmetal • Modern Rectangular',
                'category' => 'men',
                'type' => 'frame',
                'price' => 179,
                'old_price' => 219,
                'image_path' => 'frames/men/regalis.JPEG',
                'badge' => 'Sale',
                'badge_color' => '#f59e0b',
            ],
            [
                'name' => 'Stratos',
                'description' => 'Havana Brown • Round',
                'category' => 'men',
                'type' => 'frame',
                'price' => 229,
                'old_price' => null,
                'image_path' => 'frames/men/stratos.avif',
                'badge' => null,
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Titan',
                'description' => 'Carbon Fiber • Sport',
                'category' => 'men',
                'type' => 'frame',
                'price' => 299,
                'old_price' => null,
                'image_path' => 'frames/men/titan.avif',
                'badge' => 'Bestseller',
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Valen',
                'description' => 'Matte Navy • Premium',
                'category' => 'men',
                'type' => 'frame',
                'price' => 219,
                'old_price' => null,
                'image_path' => 'frames/men/valen.avif',
                'badge' => 'New',
                'badge_color' => '#eab308',
            ],
            [
                'name' => 'Vanguard',
                'description' => 'Black Metal • Edge',
                'category' => 'men',
                'type' => 'frame',
                'price' => 269,
                'old_price' => null,
                'image_path' => 'frames/men/vanguard.jpg',
                'badge' => null,
                'badge_color' => '#1a3c2e',
            ],
        ];

        $womenProducts = [
            [
                'name' => 'Aurelia',
                'description' => 'Rose Gold • Thin Metal',
                'category' => 'women',
                'type' => 'frame',
                'price' => 229,
                'old_price' => null,
                'image_path' => 'frames/women/aurelia.webp',
                'badge' => 'Bestseller',
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Celestia',
                'description' => 'Burgundy Acetate • Statement',
                'category' => 'women',
                'type' => 'frame',
                'price' => 279,
                'old_price' => null,
                'image_path' => 'frames/women/celestia.jpg',
                'badge' => 'New',
                'badge_color' => '#eab308',
            ],
            [
                'name' => 'Elysia',
                'description' => 'Cat-eye • Black with Gold',
                'category' => 'women',
                'type' => 'frame',
                'price' => 259,
                'old_price' => null,
                'image_path' => 'frames/women/elysia.avif',
                'badge' => 'Bestseller',
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Florent',
                'description' => 'Light Pink • Translucent',
                'category' => 'women',
                'type' => 'frame',
                'price' => 219,
                'old_price' => null,
                'image_path' => 'frames/women/florent.webp',
                'badge' => null,
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Lunette',
                'description' => 'Crystal Clear • Modern',
                'category' => 'women',
                'type' => 'frame',
                'price' => 179,
                'old_price' => 219,
                'image_path' => 'frames/women/lunette.avif',
                'badge' => 'Sale',
                'badge_color' => '#f59e0b',
            ],
            [
                'name' => 'Mirabelle',
                'description' => 'Lavender • Round Frame',
                'category' => 'women',
                'type' => 'frame',
                'price' => 239,
                'old_price' => null,
                'image_path' => 'frames/women/mirabelle.webp',
                'badge' => 'New',
                'badge_color' => '#eab308',
            ],
            [
                'name' => 'Roselle',
                'description' => 'Tortoiseshell • Cat-eye',
                'category' => 'women',
                'type' => 'frame',
                'price' => 249,
                'old_price' => null,
                'image_path' => 'frames/women/roselle.jpg',
                'badge' => null,
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Seraphine',
                'description' => 'Beige Cream • Oval',
                'category' => 'women',
                'type' => 'frame',
                'price' => 269,
                'old_price' => null,
                'image_path' => 'frames/women/seraphine.avif',
                'badge' => 'Bestseller',
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Veloura',
                'description' => 'Deep Teal • Velvet Finish',
                'category' => 'women',
                'type' => 'frame',
                'price' => 289,
                'old_price' => null,
                'image_path' => 'frames/women/veloura.png',
                'badge' => null,
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Virelle',
                'description' => 'Soft Pink • Cat-eye',
                'category' => 'women',
                'type' => 'frame',
                'price' => 199,
                'old_price' => null,
                'image_path' => 'frames/women/virelle.webp',
                'badge' => 'New',
                'badge_color' => '#eab308',
            ],
        ];

        foreach (array_merge($menProducts, $womenProducts) as $product) {
            Product::create($product);
        }
    }
}
