<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menProducts = [
            [
                'name' => 'Aurum',
                'description' => 'Matte Black • Classic Design',
                'category' => 'men',
                'type' => 'frame',
                'price' => 199,
                'old_price' => null,
                'image_path' => 'frames/men/aurum.avif',
                'badge' => 'Bestseller',
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Creston',
                'description' => 'Tortoiseshell • Bold Acetate',
                'category' => 'men',
                'type' => 'frame',
                'price' => 259,
                'old_price' => null,
                'image_path' => 'frames/men/creston.avif',
                'badge' => null,
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Imperio',
                'description' => 'Premium Gold Frame • Unisex',
                'category' => 'men',
                'type' => 'frame',
                'price' => 249,
                'old_price' => null,
                'image_path' => 'frames/men/imperio.jpg',
                'badge' => 'New',
                'badge_color' => '#eab308',
            ],
            [
                'name' => 'Monarch',
                'description' => 'Silver Metal • Classic Aviator',
                'category' => 'men',
                'type' => 'frame',
                'price' => 279,
                'old_price' => null,
                'image_path' => 'frames/men/monarch.jpg',
                'badge' => 'Bestseller',
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Noirline',
                'description' => 'Dark Blue • Sophisticated',
                'category' => 'men',
                'type' => 'frame',
                'price' => 239,
                'old_price' => null,
                'image_path' => 'frames/men/noirline.avif',
                'badge' => null,
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Regalis',
                'description' => 'Gunmetal • Modern Rectangular',
                'category' => 'men',
                'type' => 'frame',
                'price' => 179,
                'old_price' => 219,
                'image_path' => 'frames/men/regalis.JPEG',
                'badge' => 'Sale',
                'badge_color' => '#f59e0b',
            ],
            [
                'name' => 'Stratos',
                'description' => 'Havana Brown • Round',
                'category' => 'men',
                'type' => 'frame',
                'price' => 229,
                'old_price' => null,
                'image_path' => 'frames/men/stratos.avif',
                'badge' => null,
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Titan',
                'description' => 'Carbon Fiber • Sport',
                'category' => 'men',
                'type' => 'frame',
                'price' => 299,
                'old_price' => null,
                'image_path' => 'frames/men/titan.avif',
                'badge' => 'Bestseller',
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Valen',
                'description' => 'Matte Navy • Premium',
                'category' => 'men',
                'type' => 'frame',
                'price' => 219,
                'old_price' => null,
                'image_path' => 'frames/men/valen.avif',
                'badge' => 'New',
                'badge_color' => '#eab308',
            ],
            [
                'name' => 'Vanguard',
                'description' => 'Black Metal • Edge',
                'category' => 'men',
                'type' => 'frame',
                'price' => 269,
                'old_price' => null,
                'image_path' => 'frames/men/vanguard.jpg',
                'badge' => null,
                'badge_color' => '#1a3c2e',
            ],
        ];

        $lensProducts = [
            [
                'name' => 'Standard',
                'description' => 'Clear vision',
                'category' => 'lenses',
                'type' => 'lens',
                'price' => 0,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '👓',
            ],
            [
                'name' => 'Blue Lens',
                'description' => 'Blue light filter',
                'category' => 'lenses',
                'type' => 'lens',
                'price' => 50,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '🔵',
            ],
            [
                'name' => 'Transition',
                'description' => 'Light adaptive',
                'category' => 'lenses',
                'type' => 'lens',
                'price' => 80,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '🌫️',
            ],
            [
                'name' => 'Computer Progressive',
                'description' => 'Multi-focal',
                'category' => 'lenses',
                'type' => 'lens',
                'price' => 100,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '💻',
            ],
            [
                'name' => 'Ultra Thin',
                'description' => 'Slim profile',
                'category' => 'lenses',
                'type' => 'lens',
                'price' => 70,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '🥽',
            ],
            [
                'name' => 'Polarized',
                'description' => 'Glare reduction',
                'category' => 'lenses',
                'type' => 'lens',
                'price' => 90,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '🕶️',
            ],
        ];

        $accessoryProducts = [
            [
                'name' => 'Default Case',
                'description' => 'Standard case',
                'category' => 'accessories',
                'type' => 'accessory',
                'price' => 0,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '📦',
            ],
            [
                'name' => 'Luxe Case',
                'description' => 'Premium leather',
                'category' => 'accessories',
                'type' => 'accessory',
                'price' => 25,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '💼',
            ],
            [
                'name' => 'Leather Case',
                'description' => 'Genuine leather',
                'category' => 'accessories',
                'type' => 'accessory',
                'price' => 35,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '👜',
            ],
            [
                'name' => 'Eyeglass Chain',
                'description' => 'Stylish chain',
                'category' => 'accessories',
                'type' => 'accessory',
                'price' => 15,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '⛓️',
            ],
            [
                'name' => 'Cleaning Spray',
                'description' => 'Lens cleaner',
                'category' => 'accessories',
                'type' => 'accessory',
                'price' => 10,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '🧴',
            ],
            [
                'name' => 'Microfiber Cloth',
                'description' => 'Soft cleaning',
                'category' => 'accessories',
                'type' => 'accessory',
                'price' => 8,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '🧹',
            ],
        ];

        $womenProducts = [
            [
                'name' => 'Aurelia',
                'description' => 'Rose Gold • Thin Metal',
                'category' => 'women',
                'type' => 'frame',
                'price' => 229,
                'old_price' => null,
                'image_path' => 'frames/women/aurelia.webp',
                'badge' => 'Bestseller',
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Celestia',
                'description' => 'Burgundy Acetate • Statement',
                'category' => 'women',
                'type' => 'frame',
                'price' => 279,
                'old_price' => null,
                'image_path' => 'frames/women/celestia.jpg',
                'badge' => 'New',
                'badge_color' => '#eab308',
            ],
            [
                'name' => 'Elysia',
                'description' => 'Cat-eye • Black with Gold',
                'category' => 'women',
                'type' => 'frame',
                'price' => 259,
                'old_price' => null,
                'image_path' => 'frames/women/elysia.avif',
                'badge' => 'Bestseller',
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Florent',
                'description' => 'Light Pink • Translucent',
                'category' => 'women',
                'type' => 'frame',
                'price' => 219,
                'old_price' => null,
                'image_path' => 'frames/women/florent.webp',
                'badge' => null,
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Lunette',
                'description' => 'Crystal Clear • Modern',
                'category' => 'women',
                'type' => 'frame',
                'price' => 179,
                'old_price' => 219,
                'image_path' => 'frames/women/lunette.avif',
                'badge' => 'Sale',
                'badge_color' => '#f59e0b',
            ],
            [
                'name' => 'Mirabelle',
                'description' => 'Lavender • Round Frame',
                'category' => 'women',
                'type' => 'frame',
                'price' => 239,
                'old_price' => null,
                'image_path' => 'frames/women/mirabelle.webp',
                'badge' => 'New',
                'badge_color' => '#eab308',
            ],
            [
                'name' => 'Roselle',
                'description' => 'Tortoiseshell • Cat-eye',
                'category' => 'women',
                'type' => 'frame',
                'price' => 249,
                'old_price' => null,
                'image_path' => 'frames/women/roselle.jpg',
                'badge' => null,
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Seraphine',
                'description' => 'Beige Cream • Oval',
                'category' => 'women',
                'type' => 'frame',
                'price' => 269,
                'old_price' => null,
                'image_path' => 'frames/women/seraphine.avif',
                'badge' => 'Bestseller',
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Veloura',
                'description' => 'Deep Teal • Velvet Finish',
                'category' => 'women',
                'type' => 'frame',
                'price' => 289,
                'old_price' => null,
                'image_path' => 'frames/women/veloura.png',
                'badge' => null,
                'badge_color' => '#1a3c2e',
            ],
            [
                'name' => 'Virelle',
                'description' => 'Soft Pink • Cat-eye',
                'category' => 'women',
                'type' => 'frame',
                'price' => 199,
                'old_price' => null,
                'image_path' => 'frames/women/virelle.webp',
                'badge' => 'New',
                'badge_color' => '#eab308',
            ],
        ];

        foreach (array_merge($menProducts, $womenProducts, $lensProducts, $accessoryProducts) as $product) {
            Product::create($product);
        }
    }
}
