<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menProducts = [
            [
                'name' => 'Aurum',
                'description' => 'Matte Black • Classic Design',
                'category' => 'men',
                'type' => 'frame',
                'price' => 2990,
                'old_price' => null,
                'image_path' => 'frames/men/aurum.avif',
                'badge' => 'Bestseller',
                'badge_color' => '#1a3c2e',
                'stocks' => 35,
                'status' => 'active',
            ],
            [
                'name' => 'Creston',
                'description' => 'Tortoiseshell • Bold Acetate',
                'category' => 'men',
                'type' => 'frame',
                'price' => 2590,
                'old_price' => null,
                'image_path' => 'frames/men/creston.avif',
                'badge' => null,
                'badge_color' => '#1a3c2e',
                'stocks' => 28,
                'status' => 'active',
            ],
            [
                'name' => 'Imperio',
                'description' => 'Premium Gold Frame • Unisex',
                'category' => 'men',
                'type' => 'frame',
                'price' => 3490,
                'old_price' => null,
                'image_path' => 'frames/men/imperio.jpg',
                'badge' => 'New',
                'badge_color' => '#eab308',
                'stocks' => 40,
                'status' => 'active',
            ],
            [
                'name' => 'Monarch',
                'description' => 'Silver Metal • Classic Aviator',
                'category' => 'men',
                'type' => 'frame',
                'price' => 2790,
                'old_price' => null,
                'image_path' => 'frames/men/monarch.jpg',
                'badge' => 'Bestseller',
                'badge_color' => '#1a3c2e',
                'stocks' => 32,
                'status' => 'active',
            ],
            [
                'name' => 'Noirline',
                'description' => 'Dark Blue • Sophisticated',
                'category' => 'men',
                'type' => 'frame',
                'price' => 2390,
                'old_price' => null,
                'image_path' => 'frames/men/noirline.avif',
                'badge' => null,
                'badge_color' => '#1a3c2e',
                'stocks' => 25,
                'status' => 'active',
            ],
            [
                'name' => 'Regalis',
                'description' => 'Gunmetal • Modern Rectangular',
                'category' => 'men',
                'type' => 'frame',
                'price' => 2190,
                'old_price' => 2690,
                'image_path' => 'frames/men/regalis.JPEG',
                'badge' => 'Sale',
                'badge_color' => '#f59e0b',
                'stocks' => 18,
                'status' => 'active',
            ],
            [
                'name' => 'Stratos',
                'description' => 'Havana Brown • Round',
                'category' => 'men',
                'type' => 'frame',
                'price' => 2490,
                'old_price' => null,
                'image_path' => 'frames/men/stratos.avif',
                'badge' => null,
                'badge_color' => '#1a3c2e',
                'stocks' => 30,
                'status' => 'active',
            ],
            [
                'name' => 'Titan',
                'description' => 'Carbon Fiber • Sport',
                'category' => 'men',
                'type' => 'frame',
                'price' => 3290,
                'old_price' => null,
                'image_path' => 'frames/men/titan.avif',
                'badge' => 'Bestseller',
                'badge_color' => '#1a3c2e',
                'stocks' => 38,
                'status' => 'active',
            ],
            [
                'name' => 'Valen',
                'description' => 'Matte Navy • Premium',
                'category' => 'men',
                'type' => 'frame',
                'price' => 3190,
                'old_price' => null,
                'image_path' => 'frames/men/valen.avif',
                'badge' => 'New',
                'badge_color' => '#eab308',
                'stocks' => 22,
                'status' => 'active',
            ],
            [
                'name' => 'Vanguard',
                'description' => 'Black Metal • Edge',
                'category' => 'men',
                'type' => 'frame',
                'price' => 2690,
                'old_price' => null,
                'image_path' => 'frames/men/vanguard.jpg',
                'badge' => null,
                'badge_color' => '#1a3c2e',
                'stocks' => 15,
                'status' => 'active',
            ],
        ];

        $lensProducts = [
            [
                'name' => 'Standard',
                'description' => 'Clear vision',
                'category' => 'lenses',
                'type' => 'lens',
                'price' => 0,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '👓',
                'stocks' => 100,
                'status' => 'active',
            ],
            [
                'name' => 'Blue Lens',
                'description' => 'Blue light filter',
                'category' => 'lenses',
                'type' => 'lens',
                'price' => 990,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '🔵',
                'stocks' => 85,
                'status' => 'active',
            ],
            [
                'name' => 'Transition',
                'description' => 'Light adaptive',
                'category' => 'lenses',
                'type' => 'lens',
                'price' => 1990,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '🌫️',
                'stocks' => 60,
                'status' => 'active',
            ],
            [
                'name' => 'Computer Progressive',
                'description' => 'Multi-focal',
                'category' => 'lenses',
                'type' => 'lens',
                'price' => 2990,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '💻',
                'stocks' => 45,
                'status' => 'active',
            ],
            [
                'name' => 'Ultra Thin',
                'description' => 'Slim profile',
                'category' => 'lenses',
                'type' => 'lens',
                'price' => 1490,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '🥽',
                'stocks' => 70,
                'status' => 'active',
            ],
            [
                'name' => 'Polarized',
                'description' => 'Glare reduction',
                'category' => 'lenses',
                'type' => 'lens',
                'price' => 1290,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '🕶️',
                'stocks' => 55,
                'status' => 'active',
            ],
        ];

        $accessoryProducts = [
            [
                'name' => 'Default Case',
                'description' => 'Standard case',
                'category' => 'accessories',
                'type' => 'accessory',
                'price' => 0,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '📦',
                'stocks' => 80,
                'status' => 'active',
            ],
            [
                'name' => 'Luxe Case',
                'description' => 'Premium leather',
                'category' => 'accessories',
                'type' => 'accessory',
                'price' => 690,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '💼',
                'stocks' => 45,
                'status' => 'active',
            ],
            [
                'name' => 'Leather Case',
                'description' => 'Genuine leather',
                'category' => 'accessories',
                'type' => 'accessory',
                'price' => 990,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '👜',
                'stocks' => 30,
                'status' => 'active',
            ],
            [
                'name' => 'Eyeglass Chain',
                'description' => 'Stylish chain',
                'category' => 'accessories',
                'type' => 'accessory',
                'price' => 290,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '⛓️',
                'stocks' => 55,
                'status' => 'active',
            ],
            [
                'name' => 'Cleaning Spray',
                'description' => 'Lens cleaner',
                'category' => 'accessories',
                'type' => 'accessory',
                'price' => 190,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '🧴',
                'stocks' => 65,
                'status' => 'active',
            ],
            [
                'name' => 'Microfiber Cloth',
                'description' => 'Soft cleaning',
                'category' => 'accessories',
                'type' => 'accessory',
                'price' => 150,
                'old_price' => null,
                'image_path' => '',
                'badge' => null,
                'badge_color' => null,
                'icon' => '🧹',
                'stocks' => 90,
                'status' => 'active',
            ],
        ];

        $womenProducts = [
            [
                'name' => 'Aurelia',
                'description' => 'Rose Gold • Thin Metal',
                'category' => 'women',
                'type' => 'frame',
                'price' => 2990,
                'old_price' => null,
                'image_path' => 'frames/women/aurelia.webp',
                'badge' => 'Bestseller',
                'badge_color' => '#1a3c2e',
                'stocks' => 30,
                'status' => 'active',
            ],
            [
                'name' => 'Celestia',
                'description' => 'Burgundy Acetate • Statement',
                'category' => 'women',
                'type' => 'frame',
                'price' => 3490,
                'old_price' => null,
                'image_path' => 'frames/women/celestia.jpg',
                'badge' => 'New',
                'badge_color' => '#eab308',
                'stocks' => 20,
                'status' => 'active',
            ],
            [
                'name' => 'Elysia',
                'description' => 'Cat-eye • Black with Gold',
                'category' => 'women',
                'type' => 'frame',
                'price' => 2790,
                'old_price' => null,
                'image_path' => 'frames/women/elysia.avif',
                'badge' => 'Bestseller',
                'badge_color' => '#1a3c2e',
                'stocks' => 35,
                'status' => 'active',
            ],
            [
                'name' => 'Florent',
                'description' => 'Light Pink • Translucent',
                'category' => 'women',
                'type' => 'frame',
                'price' => 2190,
                'old_price' => null,
                'image_path' => 'frames/women/florent.webp',
                'badge' => null,
                'badge_color' => '#1a3c2e',
                'stocks' => 5,
                'status' => 'active',
            ],
            [
                'name' => 'Lunette',
                'description' => 'Crystal Clear • Modern',
                'category' => 'women',
                'type' => 'frame',
                'price' => 2190,
                'old_price' => 2690,
                'image_path' => 'frames/women/lunette.avif',
                'badge' => 'Sale',
                'badge_color' => '#f59e0b',
                'stocks' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Mirabelle',
                'description' => 'Lavender • Round Frame',
                'category' => 'women',
                'type' => 'frame',
                'price' => 2590,
                'old_price' => null,
                'image_path' => 'frames/women/mirabelle.webp',
                'badge' => 'New',
                'badge_color' => '#eab308',
                'stocks' => 25,
                'status' => 'active',
            ],
            [
                'name' => 'Roselle',
                'description' => 'Tortoiseshell • Cat-eye',
                'category' => 'women',
                'type' => 'frame',
                'price' => 2490,
                'old_price' => null,
                'image_path' => 'frames/women/roselle.jpg',
                'badge' => null,
                'badge_color' => '#1a3c2e',
                'stocks' => 18,
                'status' => 'active',
            ],
            [
                'name' => 'Seraphine',
                'description' => 'Beige Cream • Oval',
                'category' => 'women',
                'type' => 'frame',
                'price' => 3290,
                'old_price' => null,
                'image_path' => 'frames/women/seraphine.avif',
                'badge' => 'Bestseller',
                'badge_color' => '#1a3c2e',
                'stocks' => 28,
                'status' => 'active',
            ],
            [
                'name' => 'Veloura',
                'description' => 'Deep Teal • Velvet Finish',
                'category' => 'women',
                'type' => 'frame',
                'price' => 2890,
                'old_price' => null,
                'image_path' => 'frames/women/veloura.png',
                'badge' => null,
                'badge_color' => '#1a3c2e',
                'stocks' => 8,
                'status' => 'active',
            ],
            [
                'name' => 'Virelle',
                'description' => 'Soft Pink • Cat-eye',
                'category' => 'women',
                'type' => 'frame',
                'price' => 2490,
                'old_price' => null,
                'image_path' => 'frames/women/virelle.webp',
                'badge' => 'New',
                'badge_color' => '#eab308',
                'stocks' => 22,
                'status' => 'active',
            ],
        ];

        foreach (array_merge($menProducts, $womenProducts, $lensProducts, $accessoryProducts) as $product) {
            Product::create($product);
        }
    }
}
