name: 'CI: Code Quality, Linting & Testing'

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev, main ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Bootstrap Environment
        uses: ./.github/actions/setup-laravel
        with:
          php-version: '8.3'

      - name: Check Code Style (Pint)
        run: ./vendor/bin/pint --test

      - name: Static Analysis (Larastan)
        run: ./vendor/bin/phpstan analyse

  execute-tests:
    needs: linting
    uses: ./.github/workflows/reusable-ci.yml
    with:
      php-version: '8.3'